app/urls.py
from django.conf.urls import url

from . import views

app_name = 'app'
urlpatterns = [
    url(r'^$', views.main_page, name='main_page'),
    url(r'time/$', views.index, name='index'),
    url(r'dashboard', views.dashboard, name='dashboard'),

    url(r'^meeting/(?P<meeting_id>[0-9]+)/vote_choice/(?P<graded_id>[0-9]+)/$', views.meeting_vote_choice, name='meeting_vote_choice'),
    url(r'^meeting/(?P<meeting_id>[0-9]+)/results/$', views.meeting_results, name='meeting_results'),
    url(r'^meeting/(?P<meeting_id>[0-9]+)/vote_action/(?P<graded_id>[0-9]+)$', views.meeting_vote_action, name='meeting_vote_action'),
    url(r'^users_results/(?P<users_type>[A-Za-z]+)/$', views.users_results, name='users_results'),
]

grade/urls.py
from django.conf.urls import include, url
from django.contrib import admin

app_name='app'
urlpatterns = [
    url(r'^', include(('app.urls', ''), namespace="app")),
    url(r'^app/', include(('app.urls', 'app'), namespace='app')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
]

app/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
INDEX PAGE NIGGA! Time now equals
<h1>{{ time_now }}</h1>
</body>
</html>

app/templates/app/users_results.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Vote results</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
        .no_grade {
            background-color: #F9F9F9;
        }

        .bad_grade {
            background-color: rgb(230, 0, 0);
        }

        .good_grade {
            background-color: #45BF3B;
        }

        .small_sample {
            background-color: #e3e3e3
        }
        table, th, td {
            font-size: 14;
            border: 0.5px solid gray;
        }

        .logoutLblPos{
           position:fixed;
           left:10px;
           top:5px;
        }
        .mainLblPos{
             position:fixed;
             left:10px;
             top:25px;
        }
        .dashboardLblPos {
            position:fixed;
           left:10px;
           top:45px;
        }
        .studentsLblPos {
            position:fixed;
           left:10px;
           top:65px;
        }
        .teachersLblPos {
            position:fixed;
           left:10px;
           top:85px;
        }


    </style>

</head>

<body>

    <a class="logoutLblPos back" href="/accounts/logout">Log out</a>
    <a class="mainLblPos back " href="/">Main</a>
    <a class="dashboardLblPos back " href="/app/dashboard">Dashboard</a>
    <a class="studentsLblPos back " href="/app/users_results/students">Students Compare(slow)</a>
    <a class="teachersLblPos back " href="/app/users_results/teachers">Teachers Compare(fast)</a>

    <div class="container">
        <h1>{{ meeting }} </h1>
    </div>


    <br />
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                {% for tuple in tuples %}
                    <th>{{ tuple }}</th>
                {%endfor%}
                </tr>
            </thead>
            <tbody>
                {% for grade_line in grades %}
                    <tr>
                        {% for grade in grade_line %}
                            {%if grade == None %}
                                <td class="no_grade text-center">  - </td>
                            {% elif grade.1 <= 20 %}
                                <th class="small_sample text-center"> {{ grade }} </th>
                            {%elif grade.0 <= 5%}
                                <td class="bad_grade text-center"> {{ grade.0 }} from {{ grade.1 }} </td>
                            {%elif grade.0 > 5%}
                                <td class="good_grade text-center"> {{ grade.0 }} from {{ grade.1 }} </td>
                            {% else %}
                                <th> {{ grade }} </th>
                            {% endif %}
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>



</body>

</html>

app/templates/app/vote_results_for_participant.html
<html>
<head>
    <title>Vote results</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
        .no_grade {
            background-color: #F9F9F9;
        }

        .bad_grade {
            background-color: rgb(230, 0, 0);
        }

        .good_grade {
            background-color: #45BF3B;
        }
        table, th, td {
            font-size: 14;
            border: 0.5px solid gray;
        }

        .logoutLblPos{
           position:fixed;
           left:10px;
           top:5px;
      }
      .mainLblPos{
           position:fixed;
           left:10px;
           top:25px;
      }
        .dashboardLblPos {
            position:fixed;
           left:10px;
           top:45px;
        }
        .studentsLblPos {
            position:fixed;
           left:10px;
           top:65px;
        }
        .teachersLblPos {
            position:fixed;
           left:10px;
           top:85px;
        }

    </style>

</head>

<body>

    <a class="logoutLblPos back" href="/accounts/logout">Log out</a>
    <a class="mainLblPos back " href="/">Main</a>
    <a class="dashboardLblPos back " href="/app/dashboard">Dashboard</a>
    <a class="studentsLblPos back " href="/app/users_results/students">Students Compare(slow)</a>
    <a class="teachersLblPos back " href="/app/users_results/teachers">Teachers Compare(fast)</a>


    <div class="container">
        <h1>{{ meeting.meeting_type }} in {{ meeting.course }} in {{ meeting.place }} on {{ meeting.date }} </h1>
    </div>
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                {% for tuple in tuples %}
                    <th><a href="{% url 'app:meeting_vote_choice' meeting.id tuple.1 %}"> {{ tuple.0 }} </a> </th>
                {%endfor%}
                </tr>
            </thead>
            <tbody>
                {% for grade_line in grades %}
                    <tr>
                        {% for grade in grade_line %}
                            {%if grade == None %}
                                <td class="no_grade text-center">  - </td>
                            {%elif grade <= 5%}
                                <td class="bad_grade text-center"> {{ grade}} </td>
                            {%elif grade > 5%}
                                <td class="good_grade text-center"> {{ grade }} </td>
                            {% else %}
                                <th> {{ grade }} </th>
                            {% endif %}
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>



</body>

</html>

app/templates/app/vote_results_non_participants.html
<html>
<head>
    <title>Vote results</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
        .no_grade {
            background-color: #C2C2C2;
        }

        .bad_grade {
            background-color: #B42D2D;
        }

        .good_grade {
            background-color: #45BF3B;
        }
    </style>

</head>

<body>
    <div class="container">
        <h1>{{ meeting.meeting_type }} in {{ meeting.course }} in {{ meeting.place }} on {{ meeting.date }}</h1>
    </div>

    <div class="container">
        <table class="table">
            {% for grade_line in grades %}
                <tr>
                    {% for grade in grade_line %}
                        {%if grade == None %}
                            <th class="no_grade"> {{ grade }} </th>
                        {%elif grade <= 5%}
                            <th class="bad_grade"> {{ grade }} </th>
                        {%elif grade > 5%}
                            <th class="good_grade"> {{ grade }} </th>
                        {% else %}
                            <th> {{ grade }} </th>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>

</body>

</html>s

app/templates/app/voting.html
<html>
<head>
    <title>Vote results</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script>
            $(document).ready(function() {
              var activeSystemClass = $('.list-group-item.active');

              //something is entered in search form
              $('#system-search').keyup( function() {
                 var that = this;
                  // affect all table rows on in systems table
                  var tableBody = $('.table-list-search tbody');
                  var tableRowsClass = $('.table-list-search tbody tr');
                  $('.search-sf').remove();
                  tableRowsClass.each( function(i, val) {

                      //Lower text for case insensitive
                      var rowText = $(val).text().toLowerCase();
                      var inputText = $(that).val().toLowerCase();
                      if(inputText != '')
                      {
                          $('.search-query-sf').remove();
                          tableBody.prepend('<tr class="search-query-sf"><td colspan="6"><strong>Searching for: "'
                              + $(that).val()
                              + '"</strong></td></tr>');
                      }
                      else
                      {
                          $('.search-query-sf').remove();
                      }

                      if( rowText.indexOf( inputText ) == -1 )
                      {
                          //hide rows
                          tableRowsClass.eq(i).hide();

                      }
                      else
                      {
                          $('.search-sf').remove();
                          tableRowsClass.eq(i).show();
                      }
                  });
                  //all tr elements are hidden
                  if(tableRowsClass.children(':visible').length == 0)
                  {
                      tableBody.append('<tr class="search-sf"><td class="text-muted" colspan="6">No entries found.</td></tr>');
                  }
              });
          });
    </script>

    <style>
        .voter {
            height: 100px;
            width: 100px;
            text-align:center;
            padding-top: 40px;
            border-style:solid;
            border: 10px;
            border-color: black;
        }
    </style>
</head>

<body>
    <div class="container">
        <h2>{{ meeting.meeting_type }} in {{ meeting.course }} in {{ meeting.place }} on {{ meeting.date }}</h1>
        <h3> {{ graded }} graded by {{ grading }} </h3>
    </div>

    <form action="{% url 'app:meeting_vote_action' meeting.id graded.id%}" method="POST">
        {% csrf_token %}
        <div class="container">
        <div class="raw">
                <div class="col-md-1 voter" style="background-color:#F50003;">
                    <input type="radio" name="overall_grade" value="1"> 1
                </div>
                <div class="col-md-1 voter" style="background-color:#EF1F21">
                    <input type="radio" name="overall_grade" value="2"> 2
                </div>
                <div class="col-md-1 voter" style="background-color:#E84A4C">
                    <input type="radio" name="overall_grade" value="3"> 3
                </div>
                <div class="col-md-1 voter" style="background-color:#E79293">
                    <input type="radio" name="overall_grade" value="4"> 4
                </div>
                <div class="col-md-1 voter" style="background-color:#FFFFFF">
                    <input type="radio" name="overall_grade" value="5" checked> 5
                </div>
                <div class="col-md-1 voter" style="background-color:#C6DFC3">
                    <input type="radio" name="overall_grade" value="6"> 6
                </div>
                <div class="col-md-1 voter" style="background-color:#A6D4A0">
                    <input type="radio" name="overall_grade" value="7"> 7
                </div>
                <div class="col-md-1 voter" style="background-color:#81D076">
                    <input type="radio" name="overall_grade" value="8"> 8
                </div>
                <div class="col-md-1 voter" style="background-color:#51CF3F">
                    <input type="radio" name="overall_grade" value="9"> 9
                </div>
                <div class="col-md-1 voter" style="background-color:#28C412">
                    <input type="radio" name="overall_grade" value="10"> 10
                </div>
                <div class="col-md-2"></div>
        </div>
        </div>

        <br />

        <div class="containter" style="padding-left:180px; padding-bottom: 40px">
            {% for merit in merits %}
                <input type="checkbox" name="{{ merit.id }}" value='1'> {{ merit.name }}<br />
            {% endfor %}
        </div>
        <div class="container">
            <input type="submit">
        </div>
    </form>

</body>